# Generated by Django 3.1.1 on 2021-01-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_project_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='title_slug',
            field=models.SlugField(blank=True, primary_key=True, serialize=False),
        ),
    ]
