# Generated by Django 3.1.1 on 2021-01-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_screengrab'),
    ]

    operations = [
        migrations.AddField(
            model_name='screengrab',
            name='identifier',
            field=models.CharField(default='Unassigned', max_length=100),
        ),
    ]
