# Generated by Django 3.1.1 on 2021-01-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='market',
            field=models.TextField(default='default_market'),
            preserve_default=False,
        ),
    ]
