# Generated by Django 3.1.1 on 2021-02-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_project_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_logo',
            field=models.ImageField(blank=True, default='default_logo.jpg', upload_to='project_logos'),
        ),
    ]
