# Generated by Django 3.1.7 on 2021-06-02 18:04

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_project_project_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('interested_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.project')),
            ],
        ),
    ]
