# Generated by Django 3.1.7 on 2021-06-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_auto_20210602_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True),
        ),
    ]
