# Generated by Django 3.1.7 on 2021-06-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0011_auto_20210608_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.IntegerField(choices=[(0, 0), (25, 25), (50, 50), (75, 75), (100, 100)], default=0),
        ),
    ]
