# Generated by Django 3.1.7 on 2021-06-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0012_project_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='card_logo',
            field=models.ImageField(blank=True, null=True, upload_to='card_logos'),
        ),
    ]
