# Generated by Django 3.1.7 on 2021-06-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0013_project_card_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='market',
            field=models.TextField(blank=True, null=True),
        ),
    ]
