# Generated by Django 3.1.7 on 2021-06-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0015_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='assigned_project',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='client_requirement',
        ),
        migrations.AddField(
            model_name='project',
            name='requirements',
            field=models.ManyToManyField(blank=True, to='web_app.Requirement'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_used',
            field=models.ManyToManyField(blank=True, to='web_app.Tech'),
        ),
    ]
