# Generated by Django 3.1.7 on 2021-07-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0016_auto_20210623_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
